### ISSUE TITLE
FirebaseRef.auth() being deprecated

### ISSUE THREAD

**Issue by eduardonunesptoptal** [ca98am79/connect-firebase#11]
FIREBASE WARNING: FirebaseRef.auth() being deprecated. Please use FirebaseRef.authWithCustomToken() instead.

**Comment by ca98am79** [comment]
Did you get this running connect-firebase?  It looks like [it is already using `FirebaseRef.authWithCustomToken()`](https://github.com/ca98am79/connect-firebase/blob/master/lib/connect-firebase.js#L54)

**Comment by eduardonunesptoptal** [comment]
Yeah, you are right, but the code is outdated at NPM

**Comment by ca98am79** [comment]
thanks for letting me know - I just published the fix to npm
