### ISSUE TITLE
deprecation warnings on startup

### ISSUE THREAD

**Issue by bingomanatee** [ca98am79/connect-firebase#12]
getting

Fri, 02 Oct 2015 18:18:45 GMT express-session deprecated undefined resave option; provide resave option at firebase-session\store.js:7:13
Fri, 02 Oct 2015 18:18:45 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at firebase-session\store.js:7:13

when starting up with connect-firebase

**Comment by bingomanatee** [comment]
var session = require('express-session');
var FirebaseStore = require('connect-firebase')(session);
var options = require('./options.json');
var secret = require('./secret.json');

module.exports = function(app) {
    app.use(session({
        store: new FirebaseStore(options),
        secret: secret.key
    }));
};
is the startup script I'm using; 

options.json = {
  "host": "xxxxxxxxxxxxxx.firebaseapp.com",
  "token": "xxxxxxxxxxxx",
  "reapInterval": 600000
}

**Comment by ca98am79** [comment]
Hi, it looks like the default values for the `resave` and `saveUninitialized` options on express session have been deprecated - you can read more [here](https://github.com/expressjs/session).

The easiest way to silence those messages is to change your app.use to the following:

```
app.use(session({ secret: secret.key, resave: true, saveUninitialized: true, store: new FirebaseStore(options) }))
```
